image:
  repository: xinhlimage.azurecr.io/dev/ratify
  tag: latest
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
ratifyTestCert: |
  -----BEGIN CERTIFICATE-----
  MIIDAzCCAeugAwIBAgIQdbFNMJJ7bsCjFz9NTjm60TANBgkqhkiG9w0BAQsFADAW
  MRQwEgYDVQQDEwtyYXRpZnktdGVzdDAeFw0yMTExMTcwMDQxMjBaFw0yMjExMTcw
  MDQxMjBaMBYxFDASBgNVBAMTC3JhdGlmeS10ZXN0MIIBIjANBgkqhkiG9w0BAQEF
  AAOCAQ8AMIIBCgKCAQEA2qNunZGbxboQ8ZRPDcjRIwxbHvoQm154lizfnwTvhv15
  2mLptfJgpVRXTvFYpWacRath7ZNKSeIcItSTBVJtevTaH5eD46jysoy81AKKt9mf
  1zY4hATZfnQ5JlqPc0d0fztBHIqOtx6/YzJ7Ojlq89jfgundpN+hbv7R9LoH+bM5
  rkeQQtRg+ylE19ERlqypwBEz8i9vPjyb/pWHdAD9F/6kJSZ7iNvcBc5poZKoPG/+
  XXlBQd+pPRSYkROm2Fz8er/j3PmCfi9Wb7Slr1lmqeS53nedun9/0sbYE/xQwT4Z
  OcG8ki21H7gGrvYsHYNr4+7DXr/5hX6VBHqMCBcAqQIDAQABo00wSzAOBgNVHQ8B
  Af8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwDAYDVR0TAQH/BAIwADAWBgNV
  HREEDzANggtyYXRpZnktdGVzdDANBgkqhkiG9w0BAQsFAAOCAQEAkmsnbd02MQS2
  64ItCWgfa96eZtMOC4hyf/gjw5ePOILl+fke32DMiYyIoQ4C2JxUli8VVUctzM7S
  x0doF7neSz9a/M7AVdIq9cRUuc46Med1n+UqyMTXC1lvcrXszmZo3J61jOZlels0
  N7wnH3yS5UbsZLqS7A5v6+fLJBj5QIG4EPVqIACNhE4fpiChih6Louu98AQWgFG/
  HzWwHl1ycgSCK4ADh7rGyLyaSDgwTM1knzxvq0vBdKX+hS2rfVI5QGZLNi/K4qpr
  +QsmXjQo4s6vYCeUXeg/fRlNbPrcHFscDPe62gfSD/h2ziKnvGASh8JFY9jaITCn
  c92MWya0Lw==
  -----END CERTIFICATE-----
cosign:
  enabled: false
  key: ""
resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi
serviceAccount:
  create: false
  name:

# Can be used to authenticate to:
# ACR -> oras.authProviders.azureWorkloadIdentityEnabled
# Key Vault -> akvCertConfig.enabled
azureWorkloadIdentity:
  clientId:
azureManagedIdentity:
  clientId:
  tenantId:

akvCertConfig:
  enabled: false
  vaultName:
  cert1Name:
  cert2Name:
  tenantId:

oras:
  authProviders:
    azureWorkloadIdentityEnabled: false
    azureManagedIdentityEnabled: false
    k8secretsEnabled: false
    awsEcrBasicEnabled: false
