{{- if .Values.akvCertConfig.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ratify.akv.secretProviderClassName" . }}
spec:
  provider: azure
  parameters:
    keyvaultName: {{ required "vaultName must be provided when AKV cert config is enabled" .Values.akvCertConfig.vaultName  }}
    {{- if .Values.oras.authProviders.azureManagedIdentityEnabled }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true" 
    userAssignedIdentityID: {{ .Values.akvCertConfig.useridentity }}
    {{ end }}
    {{- if .Values.oras.authProviders.azureWorkloadIdentityEnabled }}
    usePodIdentity: "true"
    useVMManagedIdentity: "false" 
    clientID: {{ required "clientID must be provided when use workload identity in akv" .Values.azureWorkloadIdentity.clientId  }}
    {{ end }}
    objects:  |
      array:
        - |
          objectName: {{ required "cert1Name must be provided when AKV cert config is enabled" .Values.akvCertConfig.cert1Name  }}
          objectType: cert
          objectAlias: ratify-test.crt
        {{- if .Values.akvCertConfig.cert2Name }}
        - |
          objectName: {{ .Values.akvCertConfig.cert2Name  }}
          objectType: cert
          objectAlias: ratify-test2.crt
        {{ end }}
    tenantId: {{ required "tenantId must be provided when AKV cert config is enabled" .Values.akvCertConfig.tenantId  }}
{{ end }}