apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-configuration
data:
  config.json: |
    {
      "executor": {
        "requestTimeout": 6800
      },
      "store": {
        "version": "1.0.0",
        "plugins": [
            {
                "name": "oras"
                {{- if .Values.cosign.enabled }}
                ,
                "cosignEnabled": true
                {{- end }}
                {{- if .Values.oras.authProviders.azureWorkloadIdentityEnabled }}
                ,
                "authProvider": {
                    "name": "azureWorkloadIdentity"
                }
                {{- end }}
                {{- if .Values.oras.authProviders.azureManagedIdentityEnabled }}
                ,
                "authProvider": {
                    "name": "azureManagedIdentity",
                    "clientID": "{{ .Values.azureManagedIdentity.clientId }}",
                    "cloud": "{{ .Values.azureManagedIdentity.cloud }}"
                }
                {{- end }}
                {{- if .Values.oras.authProviders.k8secretsEnabled }}
                ,
                "authProvider": {
                    "name": "k8Secrets"
                }
                {{- end }}
                {{- if .Values.oras.authProviders.awsEcrBasicEnabled }}
                ,
                "auth-provider": {
                    "name": "awsEcrBasic"
                }
                {{- end }}
            }
        ]
      },
      "policy": {
        "version": "1.0.0",
        "plugin": {
            "name": "configPolicy",
            "artifactVerificationPolicies": {
                "application/vnd.cncf.notary.v2.signature": "all"
            }
        }
      },
      "verifier": {
          "version": "1.0.0",
          "plugins": [
            {
                "name":"notaryv2",
                "artifactTypes" : "application/vnd.cncf.notary.v2.signature",
                "verificationCerts": [
                    "/usr/local/ratify-certs"
                  ]
            {{- if .Values.cosign.enabled }}
            },
            {
                "name": "cosign",
                "artifactTypes": "org.sigstore.cosign.v1",
                "key": "/usr/local/ratify-certs/cosign.pub"
            {{- end }}
            }
          ]
      }
    }